apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpp-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vpp-frontend
  template:
    metadata:
      labels:
        app: vpp-frontend
    spec:
      containers:
      - name: vpp-frontend
        image: ghaksregistry.azurecr.io/vpp-frontend:{{ github.run_id || "latest" }}
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: vpp-frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: vpp-frontend
  ports:
  - port: 80
    targetPort: 8501
