name: Python CI 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint with Flake8
        run: |
          pip install flake8
          flake8 src tests
  test:
    runs-on: ubuntu-latest
    needs: lint 
    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Set up Python
       uses: actions/setup-python@v5
       with:
        python-version: '3.11'

     - name: Cache dependencies
       uses: actions/cache@v3
       with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
         ${{ runner.os }}-pip-

     - name: Install dependencies
       run: pip install -r requirements.txt

     - name: Run tests
       run: pytest --junitxml=tests/output/results.xml

     - name: Upload test results
       if: success() && github.event_name == 'push'
       uses: actions/upload-artifact@v4
       with:
        name: test-results
        path: ./tests/output/