name: CI on AKS Self-Hosted Runner

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: [ self-hosted, linux, mac-aks ]  # must match your runner’s labels

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Show runner details
      run: |
        echo "Runner:" $RUNNER_NAME
        uname -a
    - name: Install Azure CLI
      run: |
         # This script is provided by Microsoft to install az on Debian/Ubuntu
         curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Azure Login
      uses: azure/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}


    - name: Build & Push Backend Image
      run: |
        az acr build \
          --registry ghaksregistry \
          --image vpp-backend:${{ github.run_id }} \
          --file Dockerfile.backend .

    - name: Build & Push Frontend Image
      run: |
        az acr build \
          --registry ghaksregistry \
          --image vpp-frontend:${{ github.run_id }} \
          --file Dockerfile.frontend .

    - name: Set AKS context
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: AKS-GHAKS
        resource-group: RG-GHAKS

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/frontend-deployment.yaml